### ISSUE TITLE
No pop-up at a relatively long page

### ISSUE THREAD

**Issue by grahamperrin** [scripts-richard/reading_time#1]
At https://medium.com/@aeonmag/escape-the-echo-chamber-7ce91164421c the supposed reading time, presented by Medium, is: 

> 19 min

– but there's no pop-up from the extension. 

Are pages in the `medium.com` domain exceptional? Can you direct me to a page where the pop-up should appear? Thanks. 

## Environment

Waterfox 56.1.0_10 on FreeBSD-CURRENT.

**Comment by grahamperrin** [comment]
At https://medium.com/firefox-test-pilot/min-vid-graduation-report-9ad74dc37c1 in Firefox 59.0.2 I _do_ get a pop-up, 

> 9 min

## Version requirements

From <https://addons.mozilla.org/addon/reading-time/versions/?page=1#version-1.1>: 

> Works with Firefox for Android 48.0 and later, Firefox 48.0 and later

Is the extension tested with Firefox ESR 52.x?

**Comment by displaced-lobster** [comment]
I have only tested the extension with Firefox-Nightly and Firefox 59. However, in v1.2 I implemented the recommended method for checking for page load completion before running the script and this seems to have improved the loading for pages that take a long time.

**Comment by grahamperrin** [comment]
1.3: still no pop-up with Waterfox at https://medium.com/firefox-test-pilot/min-vid-graduation-report-9ad74dc37c1 … hmm, and for that page there's _no longer_ a pop-up with Firefox 59.0.2_7,1. 

At this GitHub page: 

- I do get a pop-up, _1 min_, with Firefox
- I don't get a pop-up with Waterfox.

**Comment by displaced-lobster** [comment]
Thanks for letting me know. I'm done testing with v1.4, just uploaded, and it now works for me with Waterfox. Reopened issue and will leave it for a few days.

**Comment by grahamperrin** [comment]
Thanks 👍 

Confirmed, working with both Waterfox and Firefox. 

```text
$ pkg info waterfox | grep Version
Version        : 56.2.0.31_3
$ pkg info firefox | grep Version
Version        : 60.0.2,1
$ date ; uname -v
Fri  8 Jun 2018 18:36:41 BST
FreeBSD 12.0-CURRENT #3 r334382: Thu May 31 01:37:12 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
```
